[package]
name = "impral"
version = "0.1.0"
authors = ["Longor1996 <lalongok@gmail.com>"]
edition = "2018"

[dependencies]
smallvec = "1.6.1"
smartstring = "0.2.9"

[dependencies.tagged-box]
version = "0.1.1"
default-features = false
features = ["57bits"]
